### ISSUE TITLE
zopflipy lacks documentation, and has naming conflicts

### ISSUE THREAD

**Issue by Borketh** [hattya/zopflipy#3]
### Naming mixup
While the package name is `zopflipy` on PyPI, the import name is zopfli, which makes automated poetry dependency runs get the `zopfli` package, which is entirely different

### Doesn’t even work
![8277A7B6-7ADC-46F8-9A68-72152485DF06](https://user-images.githubusercontent.com/80119007/141838270-4007372d-3a39-4b9a-b28f-5b8a2066ff85.jpeg)

This package is the best option I have for using zopfli on a zlib zipfile, as it adds functionality to ZipFile, but it doesn’t appear to work.

**Comment by Borketh** [comment]
### Code that broke it
```py
from zipfile import ZIP_DEFLATED
from zopfli import ZipFile


with ZipFile("READ.zip") as zr:
	with ZipFile("WRITE.zip", 'w', ZIP_DEFLATED, True, 9) as zw:
		for zi in zr.infolist():
			zw.writestr(zi, zr.read(zi))
```

**Comment by Borketh** [comment]
Looks like it’s documentation time! Turns out that migrating from regular `zipfile.ZipFile` to `zopflipy.ZipFile` has some pitfalls. One major of which being that supplying a numeric level like to zlib breaks shit, because there is no `compress_level` argument in zopfli’s child class.

If you want, I can PR at some point and make `zopfli.ZipFIle` docs for the readme, because they aren’t even mentioned there and are arguably the best feature of this package.

**Comment by hattya** [comment]
I've improved compatibility of `ZipFile` with `zipfile.ZipFile` (f79424a1a543cbd23b6ab30ab322ce8b20ff588c), and I've also updated README.rst to mention `ZipFile` (80ad56ed1cfe9859ede5dd11fd5e72581857ea7c).
