### ISSUE TITLE
Wheels for Linux and macOS

### ISSUE THREAD

**Issue by flozz** [hattya/zopflipy#4]
Hello,

Currently, you only distribute wheels for Windows (`x86_64` and `win32`), but it would be great to add some for Linux (`x86` and `x86_64` × `libc` (manylinux) and `musl` (musllinux)) and for macOS (`x86_64`, `arm64` and `universal2`). The wheels can easily be built on Github Actions.

If you are interested, I can open a PR with the corresponding workflow. As an example, here is a Github Actions workflow for one of my packages:

https://github.com/wanadev/imagequant-python/blob/master/.github/workflows/python-packages.yml

(this workflow build the source (sdist) package, the wheels for Windows, Linux and macOS and then it publish automatically the result on PyPI, but it is possible to download all the wheel from the job and to publish them manually if you prefer)

**Comment by hattya** [comment]
I've set up [`pypa/cibuildwheel`](https://github.com/pypa/cibuildwheel) (fd380f479d5c802e5db2121b7a089e09f1fa9bb2), and I'll upload wheels for Linux and macOS starting from the next release.

**Comment by flozz** [comment]
Thank you! :D
